### ISSUE TITLE
Control of text - allow individual rows to be in bold font

### ISSUE THREAD

**Issue by marcel111** [dankelley/plan#10]
It would be helpful to be able to control the text on the left side of the Gantt chart more. Can we allow users to specify font weight (bold vs regular) for individual rows of text on the left side of the plot? Motivation: can apply bold font to certain items to distinguish them as headers, to help organize timeline items
Thanks!

**Comment by dankelley** [comment]
This should work now in the `develop` branch. Below is a screenshot. Perhaps you can build from the github source, and look through the documentation to see if it makes sense. I invented a new argument to `plot(gantt)`.  (Actually, I reworked a lot of the underlying code in `plan`, because it was written with S3 objects and I think S4 objects are better, etc.)

If you think this solves the problem, please close the issue. If not, please state what you would like to be different. I am also keen to hear whether you like the new argument, and whether the text I wrote for it makes sense ... now's the time to fix these things, before people start using them.
<img width="1254" alt="screen shot 2016-05-18 at 6 06 39 pm" src="https://cloud.githubusercontent.com/assets/99469/15375065/a308e26c-1d23-11e6-8631-851b29b7d461.png">

**Comment by dankelley** [comment]
This works, and it has been 3 days since I invited the requester to assess the change, so I'm closing this issue.
