### ISSUE TITLE
ylabel format feature request

### ISSUE THREAD

**Issue by bioinfowlad** [dankelley/plan#17]
How to have the ylabel show up inside the bar.

**Comment by dankelley** [comment]
Do you mean for a gantt diagram? You want a label inside the gray region as pointed to in the image below? If so, that is not in the software, and I don't think it makes sense because it would only work for long bars. If you mean inside the plot area, that could be added as an option.
<img width="836" alt="screen shot 2018-02-07 at 7 33 14 am" src="https://user-images.githubusercontent.com/99469/35914509-de70c544-0bd9-11e8-81db-ca4d5c37f384.png">

**Comment by dankelley** [comment]
This issue seems to have gone stale, so I'm closing it.
