### ISSUE TITLE
Plan gantt charts - color items

### ISSUE THREAD

**Issue by marcel111** [dankelley/plan#3]
Great package! Can plan be modified to allow users to change colors of
* [x] event bars -- already exists; args are ``col.done`` and ``col.notdone``
* [ ] chart area -- I don't know what this means ... just the box?
* [x] chart background -- added; use the ``bg`` argument

**Comment by dankelley** [comment]
Hi, and thanks for these issue reports. I will make changes to the ``develop`` branch, so you should get up to speed on installing that, if you've not done so already. You do this as follows
```r
library(devtools)
install_github(“dankelley/plan", ref="develop”)
```
If you do that and then do ``?plot.gantt``, you will notice that I have a few colour customization flags already, e.g.
```
col.done = gray(0.3), col.notdone = gray(0.9),
col.event = gray(0.1), col.connector = "black",
```
so I think a bit is done already.

**Comment by dankelley** [comment]
In the ``develop`` branch (commit 0240ba4e1dd2832a5a564be694eeccc8ad382f21) the ``plot.gantt()`` function has a new argument ``bg``. Does this do what you want, or did you want to colourize just inside the plot box?  I tend to use white backgrounds exclusively, so I'm not sure what would be wanted. If you want just inside the box, I'll add another new argument, because I think what I've done so far is what users expect from the ``par()`` argument named ``bg``.

PS. I'm editing your initial comment to make a checklist. Those are very helpful because then I and users can see the fraction that's been done, in the issue listing.

**Comment by marcel111** [comment]
The background function works great. Yes, it would be good to be able to independently adjust the fill color of the box (i.e., the portion of the chart with the bars).

**Comment by dankelley** [comment]
@marcel111, I am closing this because it is so old. I never did understand the just-previous comment. If you still need whatever it is, please open a new issue, ideally with a clear statement of the request. It helps a lot to have a diagram ... a cell-phone photo of a pencil sketch is idea and easy.
