### ISSUE TITLE
Plan gantt charts - font

### ISSUE THREAD

**Issue by marcel111** [dankelley/plan#7]
Can plan be modified to allow user to select
* [x] task font type
* [x] task font color
* [x] task font size
* [x] event line colour (called ``col.eventLine``)
* [x] event line width (called ``lwd.event``)
* [x] event line type (called ``lty.event``)
* [x] event font type (called ``font.event``)
* [x] event text color (called ``col.event``)
* [x] event text size (called ``cex.event``)

> @marcel111 I made a list and added things I guessed you mean by 'etc' in your initial comment. I'll add text to the list as I do things, and tick them off once committed to ``develop`` branch.

**Comment by marcel111** [comment]
Can plan be modified to allow user to select font types, color, size, etc?

**Comment by dankelley** [comment]
@marcel111 I have done items for events. I think we should get a check on these before we move on. Can you try the ``develop`` branch, example 5 given by ``help("plot.gantt")`` and report back on whether what I've done is sufficient?  (I've sent instructions in another issue comment on how to install the ``develop`` branch.)  Also, please feel free to list new things that will be needed, but only related to fonts and lines, for now. I will add things to the checklist (since I don't think GH gives you permission to alter existing comments) and I'll put notes there as I get them done. Note that I will quite often delete or edit comments, because I like to keep issues to 1 or 2 browser page shifts so I can see what I'm dealing with, e.g. the past few sentences of the present comment will get emailed after you add a comment.

**Comment by dankelley** [comment]
I think this is now fixed in `develop`. @marcel111, if you agree, please close this. If it is broken, please add a comment so I'll know this is still active. Thanks!

**Comment by dankelley** [comment]
I am closing this because it has been fixed for 3 days, and the original reporter has not suggested otherwise.
