### ISSUE TITLE
Control of text - allow rows with no timeline

### ISSUE THREAD

**Issue by marcel111** [dankelley/plan#9]
It would be helpful to be able to control the text on the left side of the Gantt chart more. Can we allow individual rows to have no corresponding timeline bar? Motivation: these items can serve as headers. Items below the header, with corresponding timebars, can be list items falling under the header. Thanks!

**Comment by marcel111** [comment]
[SampleGantt.pdf](https://github.com/dankelley/plan/files/268921/SampleGantt.pdf)
I added a pdf example of the desired plot

**Comment by dankelley** [comment]
This works now in `develop`.  ( @marcel111 Please see the website for how to install from github ... it was wrong the other day, which explains why it failed for both of us. ) See `as.gantt` for an example. Just set the end-time equal to the start-time (and, perhaps, alter the positioning as in `as.gantt`). Note that the positioning is not working right for me in OSX RStudio, most likely for the same reason that a lot of positioning fails in OSX RStudio (and has through about the past 4 releases ... the problem has been reported). 

Below is a screenshot showing what  example 7 from `as.gantt` gives. It's crude, but should be sufficient for simple work.

@marcel111 please close this if it has been addressed. ("It" refers to the question as posed in the title line; any nuances would be new issues, so that I can get some issues closed without losing track.) 

<img width="1059" alt="screen shot 2016-05-21 at 9 30 55 am" src="https://cloud.githubusercontent.com/assets/99469/15448399/53a22de4-1f37-11e6-8ed9-f73068f1c5dd.png">

**Comment by dankelley** [comment]
There is now an example of how to do this in the docs for `?"ganttAddTask.Rd"`, which is a new function that permits changing of existing `gantt` objects.

**Comment by dankelley** [comment]
The end of the updated vignette (in `develop` branch) now also gives an explanation how to get this feature.

**Comment by marcel111** [comment]
This works great, thanks

**Comment by dankelley** [comment]
Please close issues when you think they have been addressed. It saves me from having to ask you to close it, then checking back after N days and asking again, then closing it.
